# Generated by Django 2.1.2 on 2019-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_skill_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
