# Generated by Django 2.1.2 on 2019-01-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_poject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject',
            new_name='Project',
        ),
    ]
