# Generated by Django 2.1.2 on 2019-01-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(default='one', max_length=50),
            preserve_default=False,
        ),
    ]
